### ISSUE TITLE
細かい部分の英語修正

### ISSUE THREAD

**Issue by ArieSyVanish** [GravittoGroup/SNAKENetWork-issue#11]
News>>ニュース内容

プレイヤー名　is now AFK.

プレイヤー名　no longer AFK.

Join>>プレイヤー名　has join!

Leave>>プレイヤー名　has left!

Server>>You curretly have 9 vote

Server>>Thanks for voting at minecraft.jp

Server>>プレイヤー名 has voted in minecraft.jp

Server>>Vote for us every day for in game rewards and extras

**Comment by snake0623** [comment]
現在対応中
